const DisclaimerPolicy = () => {
    return <section>
        <div className="max-w-[1140px] m-auto bg-slate-100 bg-opacity-10 rounded-[30px]  pt-[40px] px-[60px] pb-[50px]">
            <h1 className="text-center text-[2rem] font-bold mb-[20px] ">DISCLAIMER POLICY</h1>
            <p className="text-[1.1rem]"> In no event shall WISPYDEALS.COM, its parents, associate companies, subsidiaries, affiliates,officers, directors, employees, agents or suppliers be liable for any damages whatsoever arising outof or connected with the use or performance of this website. This includes but is not limited todirect, indirect, punitive, incidental, special, and consequential damages such as loss of use, dataor profits. This also applies to any delays or inability to use the website, services provided ornot provided, and information obtained through the website. This liability extends to any virusesthat may infect a user's computer equipment. If you are unsatisfied with any part of this website orthese terms of use, your only option is to discontinue using the website.Accessing and transacting on the website is a privilege exclusively reserved for authorized users.The content on this site, including information, software, products, services and related graphics,is provided "as is" without any warranties. WISPYDEALS.COM and its suppliers make no assurancesabout the accuracy or quality of this information and hereby reject all implied warranties, such asfitness for a particular purpose, title and non-infringement.While we make every effort to keep our website consistently updated with vital information, theremay be occasions where inaccuracies or typos occur. Should this happen, WISPYDEALS.COM retainsthe right to rectify these errors. It is important to remember that any mistakes do not reflect thecompany's responsibility or liability for any decisions made based on this incorrect information.Rest assured, updates and enhancements will be made to the website as necessary.WISPYDEALS.COM and its associates, including its parents, subsidiaries, affiliates, officers,directors, employees, agents, and suppliers, will not be held liable for any damages resulting fromthe use or performance of this website. This encompasses all forms of damages such as direct,indirect, punitive, incidental, special and consequential ones - including but not limited to lossof use, data or profits. This also applies to any delays or inability to access the website orutilize its services. Furthermore, we cannot be held responsible for any potential viruses that mayaffect your computer equipment. If you are unsatisfied with any aspect of the website or these termsof use, your only course of action is to cease using the website. Please note that accessing andconducting transactions on this platform is a privilege that is reserved solely for authorizedusers. </p>
        </div>
    </section> 
};

export default DisclaimerPolicy;