const PrivacyPolicy = () => {
  return (
    
      <section className="text-[0.75rem] p-[20px]  md:mx-[40px] md:my-[20px] sm:m-[10px] sm:p-[20px] lg:text-[1 rem] md:p-[20px] md:bg-white shadow-lg rounded-2xl md:text-[0.85rem] sm:text-[0.8rem] lg:text-[1rem]">
        <h1 className="lg:text-[2.5rem] text-[1.8rem] text-center font-bold text-blue-600 mb-6">PRIVACY POLICY</h1>

        <div className=" ">
          <p>Hello, I would like to introduce myself.</p>
          <p>This Privacy Policy pertains to the handling and safeguarding of personal information collected by <span className="font-semibold">wispydeals.com</span> (operated by Almar International Limited, hereinafter referred to as "f") from Users who have purchased or inquired about any products or services through various interface channels (including but not limited to the website, mobile site, and mobile app), collectively referred to as"Sales Channels".</p>
          <ul className="my-[15px] list-disc ml-[30px] font-semibold">
            <li>The terms "you" or "your" in this policy refer to the 'User'.</li>
            <li>The use of "we", "us", or "our" in this context refers to'wispydeals.com'.</li>
            <li>The term "website" includes websites, mobile sites, and mobileapps.</li>
          </ul>
          
          <p>By utilizing our website or any other sales channels, the User acknowledges and accepts our Privacy Policy. If you do not agree,please refrain from accessing or using these channels.</p>
          <p> Kindly note that the privacy policy discussed here pertains solely to wispydeals.com and is not applicable to any external website(s), mobile site(s), or mobile app(s). We urge users to thoroughly review the information and privacy policies of our affiliated partners, advertisers, sponsors, or other websites linked by wispydeals.com as they may vary from ours. We suggest familiarizing yourself with the privacy policy of these third parties before engaging with them.</p>
          <p> We deeply respect your privacy and recognize the importance of handling and sharing personal information for both us and our users.</p>
          <p> This Policy serves to inform you of our practices regarding the collection, usage, disclosure, transfer, and storage of information. We recognize the importance of understanding these purposes and methods. In compliance with relevant data protection laws, we have created this Policy to provide transparency. It outlines the processing of your information on our Website and digital platforms. Please review this policy in conjunction with any other specific policies we may offer during the collection or processing of your personal data. Please note that this policy works alongside other notices and does not replace them.</p>
         
          <h2 className="lg:text-[1.5rem] text-[1.2rem]  font-semibold text-gray-700 mt-[20px] lg:mt-[40px] lg:mb-[10px] ">DEFINING CONTROLLER & PROCESSOR OF PERSON </h2>
          <p> The term "Controller" is used to describe the individual or entity that determines the purposes and procedures for processing personal data. This notification is being issued on behalf of wispydeals.com, acting as a controller. </p>
          <p> The Processor is any party - whether an individual or organization, including public authorities, agencies, and other bodies - that handles personal data on behalf of the Controller.</p>
          <p>In certain circumstances, wispydeals.com may serve as either the Controller or Processor of your personal information.
          </p>

          <h2 className="lg:text-[1.5rem] text-[1.2rem]  font-semibold text-gray-700 mt-[20px] lg:mt-[40px] lg:mb-[10px]">DATA COLLECTION AT WISPYDEALS.COM</h2>
          <p> Personal data refers to any information that can personally identify you as an individual. However, if your identity is removed, this information is no longer considered personal data.</p>
          <p> During any interaction with wispydeals.com, whether through our website or a third party, you may be asked to provide personal information.</p>
          <p> We collect, utilize, and share data in an aggregated form, including statistics and demographics. This type of data may include elements of your personal information but does not directly reveal your identity. For example, we may use grouped Usage Data to analyze the usage of certain features on our site. In cases where this aggregated data is combined with your personal information and can identify you directly or indirectly, we handle it as personal data and follow our policy for its use.</p>
          <p> Our company does not collect any sensitive information about you, including your race, ethnicity, religious beliefs, sexual orientation, political views, or trade union membership. This also includes data relating to your health or genetic and biometric information, as well as details about children. Additionally, we do not gather any information on criminal convictions and offences. As a reminder, we classify personal information into different categories to explain how it is used by us. These terms will be referenced in this Notice </p>
          <p> Under the category of "Contact Data," we collect personal means of communication such as residential and work addresses, email address, and telephone numbers. Similarly, under "Identity Data," we gather first names, last names, usernames, or comparable identifiers like titles. We understand that certain information pertaining to our services, including user data such as usernames and passwords, is highly confidential and security-sensitive. Additionally, when it comes to transactions on your registered wispydeals.com account, we collect data such as e-commerce activity, purchasing patterns, and bookings for other travellers. In this case, it is important for you to confirm that the other traveller(s) have given their consent for us and our service providers to access their information. As for "Marketing and Communications" data, we not only take note of your  preferences for receiving marketing materials but also track how you engage with them in order to enhance our services and provide more relevant information. For more details on the personal data we handle for marketing purposes, please refer to the accompanyin marketing communications that we send you. </p>
          <p> When you visit our site, we collect various types of data. This includes information from publicly available sources and third-party platforms like social media, as well as details provided by you through linked accounts (such as name, email address, friend list, and profile pictures) according to your account settings. These details will be included in your account information. </p>
          <p> - For visa services, we will need your personal data as well as any additional documents requested by the embassy, such as your passport, bank statements, completed application forms, and  photographs. </p>
          <p>- For For ex services, we will need a copy of your passport and an A2form, along with any other necessary documents to facilitate your transaction. This may also include confirming your travel plans with air tickets or a travel authentication document.</p>
          <p>  There are various ways to engage with our company. You can inquire  about a quote, make a reservation, or purchase something on our  website or by reaching out to our customer service team through  email, letters, faxes, phone calls, or in-person at our store.  Joining our community also allows you to receive our newsletter and  participate in lucky draws and surveys. Additionally, you can  connect with us through any online or offline event, promotion, or page on a third-party platform or location. Our site may also use cookies to enhance your experience. </p>
          <p> Websites utilize a range of cookies and similar technologies to enhance user experience. These tools, such as server logs and cookies, gather Technical Data on your device and browsing activity  Please see our cookie policy for details on the specific informatio collected. </p>
          <p> When accessing our Website, we collect Technical Data from source such as Google </p>

          <h2 className="lg:text-[1.5rem] text-[1.2rem]  font-semibold text-gray-700 mt-[20px] lg:mt-[40px] lg:mb-[10px]">PURPOSES OF DATA PROCESSING</h2>
          <p>  In order to provide you with the best experience possible on our  Website, your personal data will be processed for the following  reasons: </p>
          <p>  (a) Fulfilling a contract: We may need to process your personal data  in order to fulfill a contract that is currently being negotiated or  has been agreed upon, or to complete actions at your request before  finalizing the contract.</p>
          <p>  (b) Compliance with laws and regulations: We are obligated to adhere  to any applicable laws or regulations. </p>
          <p>   (c) Through the principle of "legitimate interests," we have the   right to utilize your personal information for our own benefit, as   long as it does not violate your fundamental rights. This may   involve monitoring your actions on our website or client portals in   order to maintain their security. Prior to taking any action, we   thoroughly evaluate and consider any potential impact on you, both  positive and negative. </p>
          <p>  The use of your personal data will be in compliance with the law, as  we always have a legal basis for any processing. Our primary  objective is to foster and enhance our relationship with our users,  which we achieve by utilizing your information for the following
            purposes during reservation: </p>
          <p>  By utilizing your Personal Information, including previous contact  details provided, we aim to improve the booking process. In order to  expedite this procedure for you, we may also access the list of  travellers linked to your account during the booking process. This  information serves various purposes, such as keeping you informed  about transaction progress and sending booking confirmations through  SMS, WhatsApp or other messaging services. It also ensures that you  receive updates or changes regarding your booking(s) and allows our  customer service team to reach out if necessary. Additionally, your  Personal Information may be used to confirm reservations with  service providers and tailor the content on our website, mobile site  and mobile app. We may also request for product or service reviews  in order to improve our offerings and send verification messages or  emails. Rest assured, this information is solely utilized for  verifying and authenticating your account to prevent any misuse or abuse. Furthermore, on special occasions such as your birthday or anniversary, we may contact you with a special gift or offer</p>
          <p> We will communicate important updates regarding our products and services, as well as any changes to our terms and policies. We may also send you information about offerings from wiapydeals.com and its affiliates, payment reminders, and travel vouchers. Additionally, we may send newsletters to keep you informed about the travel industry. If you no longer wish to receive these communications, simply unsubscribe using the link provided in the email. Please note that we may share your personal data with third parties for purposes such as processing bookings and enquiries, fulfilling service offerings, or managing customer data.</p>
          <p>  Your personal information is important to us, and we take our  responsibility to protect it seriously. As a registered user, you  will receive updates on our new products, services, promotions, and  events. However, if you wish to stop receiving these communications,  you can unsubscribe at any time. We may also use your personal data  for internal purposes such as research and analysis. We occasionally  run promotions where we may ask for contact information and survey  responses in order to notify winners and improve future campaigns.  Our travel referral or reward programs may also require the use of  your personal information for enrollment and reward delivery. But  don't worry - if you choose not to participate in these programs,  you can opt out at any time. Please note that we may verify customer  information for fraud protection purposes when rewarding users.</p>
          <h2 className="lg:text-[1.5rem] text-[1.2rem]  font-semibold text-gray-700 mt-[20px] lg:mt-[40px] lg:mb-[10px]">NON-PERSONAL DATA COLLECTION AND USAGE</h2>
          <p> Through customer activities on our portals, we gather non-personal data that cannot identify individuals. This data is used for research and analysis, as well as to improve and track the quality of our products. It may also be shared with third parties in an aggregated form to enhance customer experiences and service offerings.</p>

          <h2 className="lg:text-[1.5rem] text-[1.2rem]  font-semibold text-gray-700 mt-[20px] lg:mt-[40px] lg:mb-[10px]"> COOKIE USAGE AND OTHER TECHNOLOGIES</h2>
          <p> To enhance your overall experience on our Website, we utilize various technologies, including cookies. For your convenience, a cookie policy has been established for you to familiarize yourself with our methods, which can be accessed at any time.</p>
          <p> Our website provides convenient access to external sites. Once you click on these links, you will be directed to a different site. It is important to note that we are not responsible for the content or privacy policies of these third-party sites. We suggest reviewing the privacy policies of any external sites you visit, as they will govern your visit there </p>

          <h2 className="lg:text-[1.5rem] text-[1.2rem]  font-semibold text-gray-700 mt-[20px] lg:mt-[40px] lg:mb-[10px]">SHARING OF YOUR PERSONAL DATA</h2>
          <p> To improve personalization and optimize service delivery, we may securely share your Personal Information with other entities within our group. Additionally, in the event of a sale or transfer of wispydeals.com, your information may be passed on to the acquiring party. Similarly, should we decide to sell, transfer, or assign our business or any subsidiaries for business growth or other purposes, customer information (including Personal Information collected here) will also be transferred accordingly.</p>
          <p> At wispydeals.com, we prioritize the protection of your privacy. Your personal information will only be shared with necessary service providers and suppliers involved in fulfilling your booking. Rest assured that we do not share your information for any other purposes and do our utmost to safeguard it at all times.</p>
          <p> Information collected from users may be shared with our affiliates or business partners who offer a variety of products and services aimed at enhancing the travel experience for wispydeals.com customers. These services, which may be free or paid, can include savings on travel expenses, EMI options, co-branded credit cards, travel insurance, and coverage for lost documents. If you choose to use any of these services from our partners, their privacy policies will apply.</p>
          <p> In addition, wispydeals.com may disclose your Personal Information to third parties for tasks such as payment processing, data hosting, and data processing platforms. We may also share non-personal data derived from this information with suppliers, advertisers, affiliates, and other current and potential business partners. This aggregate data may provide insights on website interactions for these third parties.</p>
          <p> Occasionally, wispydeals.com may enlist a third party to conduct market research or surveys. In these cases, we will share information (including aggregate cookie and tracking data) under strict confidentiality agreements. This information is strictly for the completion of the designated project and must be used in accordance with relevant regulations.</p>
          
          <h2 className="lg:text-[1.5rem] text-[1.2rem]  font-semibold text-gray-700 mt-[20px] lg:mt-[40px] lg:mb-[10px]">DISCLOSURE OF INFORMATION</h2>
          <p> We may share your personal information with third parties, as required by our professional obligations and contractual agreements. This includes:</p>
          <ul className="list-disc ml-[30px] mt-[10px]">
            <li>Legal or regulatory entities such as courts, government agencies, tax authorities, law enforcement agencies.</li>
            <li>Our team of professionals who provide services such as legal advice, banking support, auditing, accounting, and insurance to our company.</li>
            <li>Service providers responsible for our IT and system administration.</li>
          </ul>

          <h2 className="lg:text-[1.5rem] text-[1.2rem]  font-semibold text-gray-700 mt-[20px] lg:mt-[40px] lg:mb-[10px]"> INTERNATIONAL TRANSFER</h2>
          <p> As wispydeals.com operates globally, it is possible that our associated companies and other parties in countries like the United States may have varying data protection standards compared to your home country. Please note that we will take necessary steps to ensure that these recipients comply with relevant laws and maintain adequate security measures for your personal information. This may involve implementing contractual safeguards in line with applicable regulations.</p>
          <p> At wispydeals.com, we offer various ways for users to share their experiences, such as through reviews, blog articles, ratings, and poll questions. You can also provide feedback or ask questions about our services and engage with other users. Occasionally, we may invite third-party assistance to gather feedback on your recent booking, but participation is entirely optional. Please note that you may receive requests for reviews via email, app notifications, SMS messages, or other messaging platforms. These reviews can be in written or video form and will be publicly visible on our site and potentially on other travel-related platforms. The User Generated Content we collect falls into the following categories:</p>
         <h2 className="lg:text-[1.5rem] text-[1.2rem]  font-semibold text-gray-700 mt-[20px] lg:mt-[40px] lg:mb-[10px]">REQUIRED PERMISSIONS FOR USING OUR MOBILE APPLICATIONS</h2>
          <p> Upon installing the wispydeals.com app on your device, a list of necessary permissions will be displayed. These permissions allow the app to function properly and access certain information. Here is an overview of the permissions we require for our Android users:</p>
          <p> - Location: By granting this permission, the app can provide you with nearby branch information for any in-person travel assistance you may need.</p>
          <p> - SMS: Allowing us to access your SMS enables us to send you OTP notifications and information about holiday packages directly to your mobile number</p>
          <p> - Phone: The app needs access to make phone calls so that you can easily contact our customer service centers through the app.</p>
          <p> - Contacts: If granted, this permission allows us to offer social features such as sharing holiday packages with friends.</p>
          <p> Additionally, some of the app's features require these permissions in order to store and save images and documents, resulting in a smoother browsing experience for future use. This means that your device won't have to constantly re-download the same content every time you access the app.</p>
          <p> In regards to IOS permissions, by opting to receive notifications, you grant us permission to directly send you exclusive deals, promotional offers, and travel-related updates to your device.{" "}</p>
          <p> With information protection and security in mind, we take into account the cost of implementation and the specific circumstances of processing in order to ensure a suitable level of security. This includes measures such as pseudonymisation and encryption of personal data, maintaining the confidentiality and integrity of processing systems and services, having a process in place for restoring access to data in a timely manner in case of incidents, and regularly testing the effectiveness of our security measures.</p>
          <p>We offer training and information to individuals with permanent or regular access to personal data, those involved in processing it, or contributing to the development of tools used for processing. This ensures their understanding of rights and responsibilities when handling your data.</p>
          <p> To protect your personal information and prevent unauthorized access, we have implemented secure measures and obtained necessary certifications. Our website is SSL-certified for secure transmission during online transactions. We strongly encourage using this feature for your protection.</p>
          <p> We expect third parties handling your information to provide equivalent levels of protection.</p>
          <p> While our system is not completely impenetrable, we continually implement internet security measures to safeguard your data in our care. By engaging with, accessing, or utilizing this site for transactions or storing personal information, you consent to adhere to our most recent privacy notice. Please note that if you use any third-party social media or service collecting your information, their terms of use and privacy policy will apply</p>
          <h2 className="lg:text-[1.5rem] text-[1.2rem]  font-semibold text-gray-700 mt-[20px] lg:mt-[40px] lg:mb-[10px]"> PERSONAL DATA RETENTION</h2>
          <p> Your personal information will be stored for the necessary duration to fulfill its intended purposes, which may include meeting legal obligations, conducting legal proceedings, or defending against potential claims. Our document management, retention, and destruction policy, along with applicable laws, dictate how long your data will be kept in our databases. This duration may extend past your relationship with us but will only be for as long as necessary to address any potential future issues that may arise. For example, we may need to retain information to provide credit for a cancelled trip you purchased. Additionally, we may keep certain data to prevent fraud, protect ourselves from liability, pursue remedies or limit damages if required by law or regulation. At times, we may also use your personal data anonymously for research or statistical purposes without notifying you beforehand. In these cases, the information will be rendered unidentifiable and retained indefinitely</p>

          <h2 className="lg:text-[1.5rem] text-[1.2rem]  font-semibold text-gray-700 mt-[20px] lg:mt-[40px] lg:mb-[10px]"> AMENDMENTS TO THE POLICY</h2>
          <p> We reserve the right to make changes or revisions to this Policy as needed. In the event of any noteworthy modifications, we will promptly inform you through email or by prominently displaying the updated policy on our website. It is advisable to periodically review this page. By continuing to use our website after any alterations have been published, you acknowledge and accept the updated terms. </p>
          <p> Your rights include certain protections under data protection laws for your personal information. Our policy is to uphold these rights and adhere to all relevant laws, rules, and regulations when handling your data. Specific details about your rights under the General Data Protection Regulation (GDPR) are outlined below:</p>
          <p> You have the right to request a copy of your personal data in a commonly used electronic format under certain circumstances. This includes information that you have provided to us, such as by completing a form or providing information through our website. Additionally, any data gathered through monitoring your behavior is also subject to this right. Please note that this right only applies when processing is based on your consent or if it is necessary for the performance of a contract and carried out using automated means.</p>
          <p> To exercise any of the aforementioned rights, you can send a request to support@almar.hk without incurring any fees for accessing your personal data. However, if we find your request to be unfounded, repetitive, or excessive, we reserve the right to charge a reasonable fee or refuse to comply. If you have any questions or concerns regarding this policy, please reach out to support@almar.hk. Please note that in order to verify your identity and protect your personal data, we may need some specific information from you and may also contact you for further details. We aim to respond to all valid requests within fifteen days but if the request is complex or multiple, it may take longer. In such cases, we will keep you informed and updated on the progress.</p>

          <h2 className="lg:text-[1.5rem] text-[1.2rem]  font-semibold text-gray-700 mt-[20px] lg:mt-[40px] lg:mb-[10px]">CONCERNS</h2>
          <p> If you have any complaints about our handling of a Subject Access Request, please inform us and we will strive to resolve it. Our Data Protection Officer (DPO) can be reached at dpo@almar.hk. Should you be unhappy with how we handle privacy complaints, do not receive prompt acknowledgement, or find that your complaint is not adequately addressed, please contact our team at custrelations@almar.hk.</p>
          <p className="mt-6"> For further inquiries regarding this privacy notice or the handling of your personal data by wispydeals.coms, please reach out to our Data Protection Officer at our Corporate Office located in Hong Kong. Our contact details are as follows:</p>
         
          <h2 className="lg:text-[1.5rem] text-[1.2rem]  font-semibold text-gray-700 mt-[20px] lg:mt-[40px] lg:mb-[10px]">  Data Protection Officer</h2>
          <h4 className="font-semibold">Corporate Office </h4>
          <address>
            <p>Unit-S, 1/F Mau Lam Commercial Building,</p>
            <p>16-18 Mau Lam Street, Jordan,</p>
            <p>Kowloon, Hong Kong-999077</p>
          </address>
          <p className="mt-4"><span className="font-semibold">Company Registration Number:</span>469105</p>
          <p><span className="font-semibold">Business Registration Certificate:</span>53855321</p>
          <p><span className="font-semibold">D-U-N-S Number:</span> 66-339-1625</p>
          <p><span className="font-semibold">ISO/IEC 27001:2022:</span>US-ARNT-24-0410004</p>
          <p><span className="font-semibold">ISO 27701:2022:</span>US-ARNT-24-0410005</p>
          <p class="mt-4"><span className="font-semibold">E-Mail:</span>
            <a href="mailto:support@almar.hk" class="text-blue-600">support@almar.hk</a></p>
          <p><span className="font-semibold">Helpline:</span> 1-802-724-4081</p>
        </div>
      </section>
  );
};
export default PrivacyPolicy;
