const TermsAndCondition = () => {
    return <section className="text-[0.75rem] p-[20px] lg:pb-[50px] lg:pl-[30px] md:mx-[40px] md:my-[20px] sm:m-[10px] sm:p-[20px] lg:text-[1 rem] md:p-[20px]  md:bg-white shadow-lg rounded-2xl md:text-[0.8rem] sm:text-[0.85rem] lg:text-[1rem]">
                <h1 className="lg:text-[2.5rem] text-[1.8rem] text-center font-bold text-blue-600 mb-6">OUR TERMS AND CONDITIONS</h1>
                <div className=" ">
                    <p>The Website located at <span className="font-semibold">WWW.WISPYDEALS.COM</span> is owned and operated by ALMAR INTERNATIONAL LIMITED, HONG KONG. We advise carefully reviewing all terms and conditions prior tomaking any bookings through this website.</p>
                    <p>By booking with us, you assume legal obligations and your entitlement to refunds for charges made to your  credit card or paid through other agreed methods is subject to our terms, policies, and the conditionsset by each supplier. It is important that you fully comprehend and consent to all of our terms andpolicies before making a booking on our website. If you do not agree with these terms, please refrainfrom using our services.</p>
                    <p>Upon completing the payment for your booking, it is assumed that you have familiarized yourself with theapplicable terms and conditions. For any concerns, kindly reach out to us prior to making a booking. Itis advisable to periodically review this section of the Website as we may modify these terms andconditions, and your continued usage of the Website will signify your agreement with any updates.</p>
                    <p>WISPYDEALS.COM acts as a middleman for WWW.WISPYDEALS.COM, selling productsand services on behalf of various airline, wholesale, and other suppliers. Please note, we arenot the provider of these services and hold no liability for their delivery or lack thereof by anyparty. We cannot guarantee the quality or availability of any offered service or product,including promotions, airfares, and vacation packages. All travel documents are subject tothe suppliers' terms and conditions and are issued solely as agents by us.</p>
                    <p>The availability of our travel products and services, which are sold through WWW.WISPYDEALS.COM, is subject to change and may be withdrawn without prior notice.</p>
                    <p>WISPYDEALSCOM is not responsible for any negligent actions or failure to act by airlines, car rental companies, ferry operators, hotels, tour operators, or other suppliers or third parties. We reserve the right to cancel or change itineraries and reservations if necessary. If WISPYDEALSCOM is found liable in any situation where such exclusion is not possible, our liability will be limited to the value of the purchased travel arrangements. Please note that we also maintain the right to reject any booking.</p>
                    <p>Please ensure that all passengers' names are entered accurately and in accordance with their passport or other identification. Keep in mind that certain suppliers may refuse to transport individuals if their name does not match the one on your booking, and they may even cancel automatically if there is a name change. Please note that WISPYDEALS.COM will not be held liable for any losses or issues resulting from incorrect entry of passenger names or for any travel restrictions imposed by carriers.</p>
                    <p>The general terms displayed on this Website apply to all travel products and packages sold by WWW.WISPYDEALS.COM. However, additional conditions may also apply to specific products and services, as various suppliers such as airlines, hotels, and wholesalers often have their own terms and conditions. These may or may not be shown on our Website.</p>
                    <p>For instance, suppliers commonly have limitations or exclusions for liability in cases of death, injury, delay, or lost/damaged baggage. We do not have these conditions listed on our Website. Thus, it is your responsibility to directly contact the relevant travel supplier to obtain all necessary information before booking with us.</p>
                    <p>Please note that there are typically several terms and conditions established by travel suppliers or third parties for discounted or advance purchase products and services. These may involve hefty cancellation or amendment fees and sometimes do not allow any refunds for cancelled holidays or air tickets. If you have questions about these fees, please reach out to our office</p>
                    <p>Remember to carefully read and accept the terms and conditions applicable to each travel product and service before making a booking with us. If you cannot find the terms on our Website, please contact our office for more information. Ultimately, once you confirm a booking and make a payment, you are bound by Third party suppliers, such as hotels, transportation providers, and airlines, provide some of the information displayed on our website. We make an effort to ensure the accuracy of this information. However, we cannot guarantee its accuracy and are not responsible for any third-party information on our website. Our website also includes links to other websites that are maintained by third parties. We do not endorse and make no warranty or representation regarding the accuracy or completeness of the information on these linked sites. By clicking on these links, you assume all risks and we will not be held liable for any loss or damage caused by your use of third-party websites<br />If a supplier makes significant changes to a tour you have booked, you may have the option to cancel without any penalty. However, this cannot be guaranteed and is subject to the supplier's terms and conditions. By accepting tickets, coupons, exchange orders, vouchers or receipts, you are also accepting any alterations that may be made to your tour.</p>
                    <p>If a supplier makes significant changes to a tour you have booked, you may have the option to cancel without any penalty. However, this cannot be guaranteed and is subject to the supplier's terms and conditions. By accepting tickets, coupons, exchange orders, vouchers or receipts, you are also accepting any alterations that may be made to your tour. Please note that service fees may be applicable for online bookings or reservations made through the www.WISPYDEALS.COM.com Travel Centre. For more information, please consult your WISPYDEALS.COM representative upon request.</p>
                    <h2 className="text-[1.2rem] lg:text-[1.5rem] font-semibold text-gray-700 mt-[20px] lg:mt-[40px] lg:mb-[10px]">Fares and Prices</h2>
                    <p>All fares and prices quoted are subject to availability at the time of booking. Prices may change until full payment and tickets are issued. They are quoted per person, unless advised otherwise by WISPYDEALS.COM. Prices listed on the Website do not include taxes, airport charges, or additional costs such as fuel levies, internet surcharges, and seasonal fees. Whenever applicable, you will be notified of these charges upon confirmation of your booking with WISPYDEALS.COM</p>
                    <p>Please note that these taxes and charges may also change before tickets are issued. Some airport taxes must be paid separately by the traveller. Airlines and third-party providers of travel services have the right to modify their fares, prices, packages, flights, and other information displayed on our Website at any time. All products, services, and information are subject to change without notice.</p>
                    <h2 className="text-[1.2rem] lg:text-[1.5rem] font-semibold text-gray-700 mt-[20px] lg:mt-[40px] lg:mb-[10px]">Travel Documents</h2>
                    <p>As a single traveler, it is your duty to have the appropriate passport, visa, and health prerequisites for your journey. Keep in mind that all departures from India necessitate a valid passport with at least 6 months of validity. If you are using a foreign passport, an Indian re-entry visa is also necessary. Be assured that we are available to aid you with this procedure.</p>
                    <p>WISPYDEALS.COM provides discounted prices to travelers on select products as a way to promote and maintain loyalty among our recurring customers. Please note that these discounts are at the company's discretion and may be declined or removed without prior notice.</p>
                    <p>You agree to abide by the terms and only utilize the Website for permitted purposes. The responsibility falls on you to provide your own equipment and software in order to access the Website. As per these terms, refrain from engaging in any activities that violate laws, infringe upon third-party rights, or are otherwise unlawful. Moreover, avoid using the Website or any associated services for surveys, contests, pyramid schemes, or sending unsolicited messages. Any attempts to gain unauthorized access or create a false identity will not be tolerated. Additionally, do not tamper with the operation of the Website or transmit viruses knowingly. The buying and selling of goods or services on the Website is prohibited as is collecting personal information without consent. Please note that external links may be present on our website but they are not under our control and we hold no liability for their content. Lastly, we reserve the right to monitor and disclose any information from the Website as required by law or governmental request.</p>
                    <p>For your protection, our Website's online booking services utilize Secure Sockets Layer (SSL) encryption. This ensures the security of all transactions made through our online booking system. Please note that SSL is always enabled when submitting information to us via the internet.</p>
                    <p>The photographs, illustrations, and other promotional materials featured on this Website serve only as a means of promotion. They do not depict any benefits that will be included in your arrangements. </p>
                    <p>The intellectual property rights of the Website and its content belong to us or our licensors, unless otherwise stated. You are granted access to the Website for personal and noncommercial purposes only. Without our permission, you may not store, distribute, perform, communicate to the public, adapt, or create derivative works from any part of the Website or commercialize any information or services obtained from it. Any trademarks used on the Website are either our trademarks or those of a third party and do not grant you permission to use them without proper authorization. You must refrain from using our trademarks as part of your own trademark, in connection with goods or services that are not ours, in a confusing, misleading, deceptive manner, or in a way that disparages us, our information or services, or the Website.</p>
                    <p>To our loyal newsletter subscribers, we offer the most up-to-date travel bargains, updates, and promotions. From time to time, we may also send out extra newsletters to inform you of exclusive deals or limited-time offers. Rest assured that your email address is only used for this purpose and will not be shared with any external parties. If you wish to stop receiving our newsletter, simply click "unsubscribe" on our Home page, send us an email at support@almar.hk, or call 1-802-724-4081. </p>
                    <p>The content on this Website has been carefully reviewed by ALMAR INTERNATIONAL LIMITED to ensure its accuracy. Despite our efforts, we cannot guarantee the complete accuracy of the information presented here. Thus, we will not be held responsible for any losses or damages resulting from errors, inaccuracies, or omissions in the content on this Website. In addition, ALMAR INTERNATIONAL LIMITED will not be liable for any data distortion caused by technical issues such as transmission errors, defects, interruptions, external interference, or viruses.</p>
                    <p>ALMAR INTERNATIONAL LIMITED cannot guarantee uninterrupted access to this Website and will not be held responsible for any losses, costs or damages resulting from possible disruptions or delays in accessing the site. We exclude all warranties, conditions and representations about the Website, its availability, and the services and information provided on it to the extent allowed by law. If a term implied by law is prohibited from being excluded or modified in a contract, it will be included in these terms. However, our liability for breaching such a term will be limited to either providing the relevant services again or reimbursing you for the cost of having them provided again. To the fullest extent permitted by law, we and our officers, employees, agents, or related bodies corporate will not be liable (whether under contract, negligence or otherwise) for any loss, damage, costs or expenses incurred by you or claims made against you in relation to your use of this Website.</p>
                    <p>The use of this Website and any materials downloaded from it are at the user's own risk. We cannot guarantee that it will not cause damage to any property, including loss of data, viruses, Trojan horses, or other harmful elements. Any information or materials shared by others on this Website, including defamatory, offensive, or illegal content, is not our responsibility. We do not accept liability for any interruptions or failures in accessing the Website. Additionally, we are not liable for any losses or damages resulting from unauthorized changes made to the content of this Website by third parties in a manner that may confuse, mislead, or deceive.</p>
                    <p>Privacy is a top priority for us. By sharing your thoughts, ideas, and materials with us through messages or feedback on the Website, you agree that we may use them without restriction, while still upholding our obligations in regards to privacy as outlined in the ALMAR INTERNATIONAL LIMITED privacy statement. It is important to note that although our trusted local suppliers comply with applicable privacy laws, some third parties outside of our control, such as hotels or car rental companies, may not have similar policies in place. We recommend reviewing the privacy policies of any websites you visit through links on our site, as their standards may differ from ours. In cases where we believe these terms have been violated, we reserve the right to immediately suspend, terminate or limit access to the Website and its services.</p>
                    <p>Cookies are a widely accepted practice for storing small pieces of data on computer systems. They can be used by any web server, including this one, to store information on your browser or request it from the browser. These cookies may serve various purposes such as displaying advertisements or tracking usage patterns to provide personalized information and improve services on your future visits to our website. In order to enable this functionality, we may place cookies on your computer</p>
                    <h2 className="text-[1.2rem] lg:text-[1.5rem] font-semibold text-gray-700 mt-[20px] lg:mt-[40px] lg:mb-[10px]">TERMS OF USE</h2>
                    <p>By using the WWW.WISPYDEALS.COM website ("Website"), you agree to these terms and conditions. The Website is owned and operated by ALavailability, and reservations for various services, such as flights, hotels, and holiday packages across India (collectively referred to as "Service"). This Service can be used by you, your family members, and friends through our vendors ("Service Providers") throughout the year.</p>
                    <p>This Agreement sets out the terms and conditions for using our Services through the Website. Depending on which Service you use, you may also need to read and accept that particular Service's terms of service ("TOS"), which may be updated or changed by WWW.WISPYDEALS.COM. These TOS are considered a part of this Agreement, and in case of any conflict between them and this Agreement, this Agreement will prevail.</p>
                    <p>To use the Website, you must agree to all the terms and conditions mentioned in this Agreement as well as any TOS that may be posted on the Website from time to time. By using the Website, you acknowledge and accept these terms and conditions. If you doMAR INTERNATIONAL LIMITED, a company based in Hong Kong. Through the Website, you can access travel information, pricing.</p>
                    <h2 className="text-[1.2rem] lg:text-[1.5rem] font-semibold text-gray-700 mt-[20px] lg:mt-[40px] lg:mb-[10px]">AMENDMENT OF TERMS AND PRIVACY POLICY</h2>
                    <p>www.holidaywaves.com maintains the right to modify the terms, conditions, and notices governing the Services offered on the Website, including charges for such Services. Users are advised to regularly review these policies.</p>
                    <p>The User acknowledges having read and comprehended Annex 2 of the Privacy Policy for WWW.WISPYDEALS.COM regarding the Website. By using the Website, the User agrees toaccept and comply with all terms outlined in the Privacy Policy. </p>
                    <p>As a Limited User, you are agreeing not to engage in any type of commercial activity with the Service, such as selling, trading, or exploiting any part of it. It's important to note that the Website is intended for personal use only and should not be used for commercial purposes. Additionally, you must not attempt to reverse engineer, modify, copy, distribute, or sell any information or products obtained from the Website. While limited reproduction and copying of content is allowed as long as Almar International is credited as the source, using the content for unlimited or wholesale reproduction or unauthorized modification is strictly prohibited</p>
                    <p>At any time and without notice, www.holidaywaves.com may choose to terminate access to the website and its related services, at its own discretion.</p>
                    <p>In the case of any part of this Agreement being deemed invalid or unenforceable, it only applies to that specific provision and the rest of the agreement remains in full effect.</p>
                    <h2 className="text-[1.2rem] lg:text-[1.5rem] font-semibold text-gray-700 mt-[20px] lg:mt-[40px] lg:mb-[10px]">COMMUNICATIONS </h2>
                    <p>All communications, whether related to changes in the Terms of Service, the Service itself, or termination of Service, must be in written form and in English. They will be considered delivered if they are presented personally or through a commercial messenger or courier service. Alternatively, they may also be sent by registered or certified mail (with return receipt requested) or via email/facsimile (with confirmation of complete transmission) to the following address:</p>
                    <p>(a) Almar International - support@almar.hk or the address listed on the Website</p>
                    <p>(b) Non-registered Users - at the communication/email address provided on the application for WWW.WISPYDEALS.COM Service.</p>
                    <p>(c) Registered Users - at the communication/email address specified in their registration form.</p>
                    <p>Notice will be considered served 48 hours after being sent, dispatched, or displayed (depending on the method chosen), unless it has been brought to the attention of the sender that the email address provided is invalid.</p>
                    <h2 className="text-[1.2rem] lg:text-[1.5rem] font-semibold text-gray-700 mt-[20px] lg:mt-[40px] lg:mb-[10px]">LEGAL JURISDICTION </h2>
                    <p>The laws of Hong Kong, without consideration of conflict of laws principles, will govern this agreement and all terms of service. Any disputes arising from this agreement will be exclusively handled by the courts in Hong Kong.</p>
                </div>
           </section>
};
export default TermsAndCondition;